# Pandas Küütphanesi (Dataframe ve Series)
* ![alt text](PandasNedir.png)
* ![alt text](Pandas_read_to.png)

In [1]:
import numpy as np
import pandas as pd

## Series ve Data Frame Tanımlama

In [2]:
# Series oluşturalım
pd.Series(["Ali","Veli","Ayşe"])
# serilerde satırların bir adı ve sıra numarası var. eğer adını belirtmezsem otomatik sıra numarasını ad olarka kullanır.

pd.Series([11,22,33], index=["s1","s2","s3"]) #index parametresi ile satır adlarını verebiliriz.

s1    11
s2    22
s3    33
dtype: int64

In [3]:
#data frame
departman = pd.DataFrame(data = [
                                    (1, "Departman A"),
                                    (2, "Departman B"),
                                    (3, "Departman C")
                                ],
                                columns=["DepId", "DepAd"]
                                )

departman 
#Eğer satır ve kolon adları verilmezse otomatik sıra numarası ad olarak kullanılır. str tipinden ad olarak kullanır.

   DepId        DepAd
0      1  Departman A
1      2  Departman B
2      3  Departman C

In [4]:
# Dataframe
ekipEfor = pd.DataFrame(data = {
                        "Id":[1,2,3,4,5],
                        "Ad":["Ali","Veli","Ayşe","Fatma","Tonguç"],
                        "Cinsiyet":["E","E",None,"K","E"],
                        "Miktar":[130, None, 339,234,None]
                    }
                    
                    ,columns=["Id", "Ad","Cinsiyet","Miktar","DepartmanId"]   #kolon etiketi, eğer o kolon yoksa oluşturur ve nan basar.
                    ,index = ["İstanbul","İstanbul","Ankara","Ankara","İzmir"] #satır etiketi
                    )

#keyler otomatik olarak kolon etiketi/adı oldu.
ekipEfor

          Id      Ad Cinsiyet  Miktar DepartmanId
İstanbul   1     Ali        E   130.0         NaN
İstanbul   2    Veli        E     NaN         NaN
Ankara     3    Ayşe     None   339.0         NaN
Ankara     4   Fatma        K   234.0         NaN
İzmir      5  Tonguç        E     NaN         NaN

In [5]:
## Hakkında bilgi alalım
ekipEfor.shape #(5, 5) 5 satır 5 kolon var.
ekipEfor.size #kaç hücre var.

25

## Atama işleminde orjinali etkilenmesin diye `copy` ile atama

In [6]:
#ekip = ekipEfor #orjinali etkilenir.
ekip = ekipEfor.copy() #orjinali etkilenmez. yani ekip değişkenindeki işlemler ekipEfor değişkenini etkilemez.

## Satır etiketi alanını kolona almak

In [7]:
#ekip.reset_index(inplace=True)
ekip = ekip.reset_index() #bu işlem orjinalini etkilemediği için ya inplace parametresi kullanılır ya da tekrar üzerine atarız

## Kolon ve Satır Etiketlerini Değiştirelim

In [8]:
#ekip.columns #Index(['index', 'Id', 'Ad', 'Cinsiyet', 'Miktar', 'DepartmanId'], dtype='object')
ekip.columns = ["index",'Id', 'Ad', 'Cinsiyet', 'Miktar', 'DepId']
#ekip.index = []

#
ekip.rename(columns={"Miktar":"Uretim", "index":"Şehir"}, index = {0: "İlk kayıt"}, inplace=True) # inplace=True ile rename geçerli oldu.
ekip

              Şehir  Id      Ad Cinsiyet  Uretim DepId
İlk kayıt  İstanbul   1     Ali        E   130.0   NaN
1          İstanbul   2    Veli        E     NaN   NaN
2            Ankara   3    Ayşe     None   339.0   NaN
3            Ankara   4   Fatma        K   234.0   NaN
4             İzmir   5  Tonguç        E     NaN   NaN

In [9]:
ekip.set_index("Şehir", inplace=True) #inplace=True ile orjianlini etkileriz. yani ekip dataframei dönüşür
ekip

          Id      Ad Cinsiyet  Uretim DepId
Şehir
İstanbul   1     Ali        E   130.0   NaN
İstanbul   2    Veli        E     NaN   NaN
Ankara     3    Ayşe     None   339.0   NaN
Ankara     4   Fatma        K   234.0   NaN
İzmir      5  Tonguç        E     NaN   NaN

In [10]:
ekip.index.name = "Şehirler"
ekip.columns.name = "Kişi bilgileri"

In [11]:
ekip

Kişi bilgileri  Id      Ad Cinsiyet  Uretim DepId
Şehirler
İstanbul         1     Ali        E   130.0   NaN
İstanbul         2    Veli        E     NaN   NaN
Ankara           3    Ayşe     None   339.0   NaN
Ankara           4   Fatma        K   234.0   NaN
İzmir            5  Tonguç        E     NaN   NaN

## Kolonların Veri Tiplerini Görelim ve Değiştirelim

In [12]:
"""
412.0+ bytes
392.0+ bytes
377.0+ bytes
347.0+ bytes
"""
ekipEfor = ekipEfor.astype({
                                "Id":np.int8,  #int
                                "Miktar":np.float16,
                                "Ad":str
                            })

ekipEfor.info()  #dataframe ve kolonlar hakkında bilgi döndürür

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, İstanbul to İzmir
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Id           5 non-null      int8
 1   Ad           5 non-null      object
 2   Cinsiyet     4 non-null      object
 3   Miktar       3 non-null      float16
 4   DepartmanId  0 non-null      object
dtypes: float16(1), int8(1), object(3)
memory usage: 347.0+ bytes

## Bazı Kullanışlı fonksiyonlar

In [13]:
ekip.describe() #Sayısal alanlar hakkında temel istatistikleri sunar.
ekip.describe().T #transpose edebiliriz.exclude parametresiyle bazı kolonlar hesaplamadan çıkarabiliriz.

,count,mean,std,min,25%,50%,75%,max
Kişi bilgileri,,,,,,,,
Id,5.0,3.000000,1.581139,1.0,2.0,3.0,4.0,5.0
Uretim,3.0,234.333333,104.500399,130.0,182.0,234.0,286.5,339.0

In [14]:
#ekip.sum() #sayısal olmayan alanlardan dolayı hata verir.
ekip.count() #her bir kolonun adedeini verdi. None olmayanları saydı.

#axis verilebilir
"""
axis=0 satır boyunca işlem yap varsayılan
axis=1 sutun boyunca işlem yap
"""

ekip.count(axis=1) #satır etiketleri üzerinden gidip kolonlardaki null olmayan değerlerin adedini getirdi.

#min, max, sum, std, mean, median, cumsum vs... kullanılabilir.

Şehirler
İstanbul    4
İstanbul    3
Ankara      3
Ankara      4
İzmir       3
dtype: int64

In [15]:
ekip.nunique() #benzersiz değerleri getir. Cinsiyet alanında 2 benzersiz değer var. #axis verilebilir.

Kişi bilgileri
Id          5
Ad          5
Cinsiyet    2
Uretim      3
DepId       0
dtype: int64

In [16]:
#seri üzerinde çalışılabilir
ekip["Uretim"] #seri döndürür. Yani kolon
ekip.Uretim #aynı şey seri döndürür

#
ekip.Uretim.mean() #serinin ortalaması.

#
ekip.Cinsiyet.value_counts() #seriye özel bir fonksiyon hangi değerden kaç tane var.

#COUNT(DISTINCT KolonAdi)
ekip.Cinsiyet.value_counts().count() #kaç farklı değer kullanılmış görebiliriz.

2

### Sıralama

In [17]:
ekip.sort_index(ascending=True) #a-z sıralar. index etiketine bakar
ekip.sort_values(by="Uretim", ascending=False) #Ureitm alanına göre buyukten kucuge sırala

Kişi bilgileri  Id      Ad Cinsiyet  Uretim DepId
Şehirler
Ankara           3    Ayşe     None   339.0   NaN
Ankara           4   Fatma        K   234.0   NaN
İstanbul         1     Ali        E   130.0   NaN
İstanbul         2    Veli        E     NaN   NaN
İzmir            5  Tonguç        E     NaN   NaN

### Değere Ulaşma Yöntemleri
![alt text](PandasDegerlereUlasmak2.png)

In [18]:
ekip = ekipEfor.copy()

### Numpy Dizisine Dönüştürmek

In [19]:
dizi_ekip = ekip.values #dizi haline gelir.

#dizi_ekip.shape
dizi_ekip[0,1] #0. satır 1. kolon kesişimi

'Ali'

### `[]` ve `[[]]` kullanımı `to_frame` ve `to_list`

In [20]:
#seri
ekip["Ad"]
ekip.Ad

İstanbul       Ali
İstanbul      Veli
Ankara        Ayşe
Ankara       Fatma
İzmir       Tonguç
Name: Ad, dtype: object

In [21]:
#
#dataframe olarak 
ekip[["Ad"]] #iki köşeli parantez var
ekip[["Ad","Cinsiyet"]]

#
ekip["Ad"].to_frame() #df elde etmemizi sağladı

              Ad
İstanbul     Ali
İstanbul    Veli
Ankara      Ayşe
Ankara     Fatma
İzmir     Tonguç

In [22]:
ekip["Ad"].to_list() #o serideki yani o kolondaki elemanları liste olarak verdi.

['Ali', 'Veli', 'Ayşe', 'Fatma', 'Tonguç']

### `df[start:stop:step]` satır sıra numarasında arama yapmamızı sağlar

In [23]:
ekip[:3] #ilk 3 satır gelsin
ekip.head(3) #üstten 3 satır demek

#
ekip[-2:] #son 2 tanesi gelir
ekip.tail(2) #son 2 tanesi gelir

        Id      Ad Cinsiyet  Miktar DepartmanId
Ankara   4   Fatma        K   234.0         NaN
İzmir    5  Tonguç        E     NaN         NaN

In [24]:
ekip[2:5:2] #2satır ile 5. satır arasını 2 satırda bir ver

        Id      Ad Cinsiyet  Miktar DepartmanId
Ankara   3    Ayşe     None   339.0         NaN
İzmir    5  Tonguç        E     NaN         NaN

In [25]:
#slicerda etiket de kullanılabilir.
ekip["Ankara":"İzmir"]

        Id      Ad Cinsiyet  Miktar DepartmanId
Ankara   3    Ayşe     None   339.0         NaN
Ankara   4   Fatma        K   234.0         NaN
İzmir    5  Tonguç        E     NaN         NaN

### `df[boolen_Liste/Seri/Array]` ile filtreleme

In [26]:
ekip.shape
#
filtre_satir = [False,True,True,False,True] #satır sayısı kadar True False ürettik. True karşısında olan satır gelecek

ekip[filtre_satir]

          Id      Ad Cinsiyet  Miktar DepartmanId
İstanbul   2    Veli        E     NaN         NaN
Ankara     3    Ayşe     None   339.0         NaN
İzmir      5  Tonguç        E     NaN         NaN

### `df.iloc[satirSirasi, kolonSirasi]` ile çalışmak

In [27]:
ekip.iloc[0,1] #0.satır 1. kolon demiş oluruz.

#
ekip.iloc[0,[0,3]] #serisi döndür
ekip.iloc[[0],[0,3]] #satr [[]] ile tanımlanırsa df döner 0. satır ve 1. ile 3. kolon

          Id  Miktar
İstanbul   1   130.0

In [28]:
#slicer ve boolen birlikte
ekip.iloc[:3, [False, True,False, True,False]] #satırlar için slicer kullandık, sutun için boolen index kullandık. bu yöntemler zaten diğer tüm yöntemler içinde kullanılabilir.

            Ad  Miktar
İstanbul   Ali   130.0
İstanbul  Veli     NaN
Ankara    Ayşe   339.0

### `df.loc[SatirEtiketi, SutunEtiketi]` ile çalışmak

In [29]:
ekip.loc["Ankara", ["Ad","Cinsiyet","Miktar"]] #satır [] kullandık ancak Ankara karşılğında zaten birden fazlsa satır geldiğinde df döndü.

           Ad Cinsiyet  Miktar
Ankara   Ayşe     None   339.0
Ankara  Fatma        K   234.0

In [30]:
ekip.loc["Ankara":"İzmir", [False, True,False, True,False]] #slicer bizden etiket bekliyor. loc kullandık.

            Ad  Miktar
Ankara    Ayşe   339.0
Ankara   Fatma   234.0
İzmir   Tonguç     NaN

In [31]:
#örn.
# içerisinde ar geçen kolonları ve ad kolonu getirelim. Tüm satırlarla birlikte gelsin.
filtre_ad = ekip.columns == "Ad" #broadcast özelliği olan bir veri tipi
filtre_ar = ekip.columns.str.contains("ar") #column.str broadcast özelliğini destekleyen bir alt module

#
filtre = filtre_ad | filtre_ar #np.logical_or  # array([False,  True, False,  True,  True])
#
ekip.loc[:, filtre ]

              Ad  Miktar DepartmanId
İstanbul     Ali   130.0         NaN
İstanbul    Veli     NaN         NaN
Ankara      Ayşe   339.0         NaN
Ankara     Fatma   234.0         NaN
İzmir     Tonguç     NaN         NaN

In [32]:
#soru:
'''
    1. Sadece Ad, Cinsiyet, Uretim kolonlarını çekelim.
    2. Uretim 150'den büyük satırları getirelim.
    3. 300'den küçük üretime sahip olmayan Erkek üyeler gelsin.
    4. 150'den büyük üretime sahip olan kadın üyeler.
'''
#1.
ekip.loc[:, ["Ad","Cinsiyet","Miktar"]]

#2.
filtre_miktar = ekip.Miktar > 150
ekip.loc[filtre_miktar]

#3.
filtre_erkek = ekip.Cinsiyet =="E"
filtre_300denKucuk = ekip.Miktar < 300

filtre = filtre_erkek & (~filtre_300denKucuk) #AltGr + Ü ile ~ işarei koyduk. np.logical_not anlamına gelir. Her bir elemanın tersini verir.

ekip.loc[filtre, ["Ad","Cinsiyet"]]

#4. soru sizde.

              Ad Cinsiyet
İstanbul    Veli        E
İzmir     Tonguç        E

### `query(expression)` ile filtreleme

In [33]:
#örn: Miktarı 200'den büyük olan kadınlar gelsin.
ekip.query("Miktar > 200 and Cinsiyet == 'K'") #tek tırnak çift tırnak kullanımına dikkat

        Id     Ad Cinsiyet  Miktar DepartmanId
Ankara   4  Fatma        K   234.0         NaN

In [34]:
#örn: ortamanın üzerinde Miktara sahip olanlar gelsin
ortalama = ekip.Miktar.mean()

#ekip.query(f"Miktar > {ortalama}")
ekip.query("Miktar > @ortalama") #@ortalama ile bu isimdeki değişkein değerini çağırdık

        Id    Ad Cinsiyet  Miktar DepartmanId
Ankara   3  Ayşe     None   339.0         NaN

In [35]:
#örn: içerisinde li geçen Adlar getirelim.
#ekip.Ad.str.contains("li")
ekip.query("Ad.str.contains('li')") #zaten ekip df içinde çalışıyoruz burada kullandığımız expression python kod parçalarıdır.

          Id    Ad Cinsiyet  Miktar DepartmanId
İstanbul   1   Ali        E   130.0         NaN
İstanbul   2  Veli        E     NaN         NaN

### `isin` kullanımı

In [36]:
ekip.isin(["Ali"]) #hücre hücre True/False #bu df parçalanarak filtrelerde kullanılabilir.

#
ekip.isin({
            "Ad":["Ali","Ayşe"],
            "Cinsiyet":["E"]
}).sum().sum() #sum ile true'lar 1 kabıl edilir ve böylece bulduklarının kolon kolon adedini çekebiliriz. sum.sum ile tüm bulunan adedi alınır.

5

### `NULL (None, NaN, NaT, N/A)` değerlerine erişmek
* `isna()` veya `isnull()` ile null mı diye kontrol edilebilir.
* `notna()` veya `notnull()` ile null değil değil mi?
* `fillna()` ile null değerleri doldurabilirizi
* `dropna()` null değerleri kaldırabiliriz

In [37]:
ekip.isna() #tüm df'te null var mı hücre hücre True/False
ekip.Miktar.isna() #eleman eleman null mı diye kontrol etti.

İstanbul    False
İstanbul     True
Ankara      False
Ankara      False
İzmir        True
Name: Miktar, dtype: bool

In [38]:
#sum ile Truları toplayabilir any ile True var mı diye kontrol edebiliriz.
ekip.isna().any() #kolon kolon null varsa True döndü
ekip.isna().any().any() #bir önceki any'den dönen True/False serisinde True var mı?

True

In [39]:
ekip.isna().sum() #kolon kolın nulların adedi
ekip.isna().sum().sum() #toplamda kaç tane null var görebiliriz.

8

In [40]:
#örn. Miktar alanı null olan alanları getirelm. bunlara ortalama değeri basalım.
ekip.Miktar.isna() #bunu filtre olarak kullanalım

#kolon karşısına = ile değer ataması yapabilirsiniz. eğer bu isimde bir kolon yoka o kolon oluşur. hata vermez.
ekip.loc[ekip.Miktar.isna(), "Miktar"] = ekip.Miktar.mean()

ekip

          Id      Ad Cinsiyet   Miktar DepartmanId
İstanbul   1     Ali        E  130.000         NaN
İstanbul   2    Veli        E  234.375         NaN
Ankara     3    Ayşe     None  339.000         NaN
Ankara     4   Fatma        K  234.000         NaN
İzmir      5  Tonguç        E  234.375         NaN

In [41]:
#null değerlere otomatik değer atamak
ekip.fillna("Bilinmiyor") #ortak bir değer vermek için

#hangi kolonda null varsa ne yazsın
ekip.fillna({
                "Miktar":ekip.Miktar.mean(),
                "Cinsiyet":"Bilinmiyor",
                "DepartmanId":-1
})

C:\Users\Abdullah\AppData\Local\Temp\ipykernel_5404\3587066257.py:5: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ekip.fillna({

          Id      Ad    Cinsiyet   Miktar  DepartmanId
İstanbul   1     Ali           E  130.000           -1
İstanbul   2    Veli           E  234.375           -1
Ankara     3    Ayşe  Bilinmiyor  339.000           -1
Ankara     4   Fatma           K  234.000           -1
İzmir      5  Tonguç           E  234.375           -1

In [42]:
#dropna ile null alanlar kaldırılabilir
ekip.dropna() #içinde bir şekilde null geliyorsa o satırları kaldırır.

#
ekip.dropna(axis=1, how="any") #axis=1 kolon anlamına gelir. #how="any" varsayılan davranıştır. herhangi bir null varsa kolonu kaldırır.
ekip.dropna(axis=1, how="all") #tüm değerleri null ise o kolonu kaldırır

#axis=0 ile satır kaldırılabilir.

          Id      Ad Cinsiyet   Miktar
İstanbul   1     Ali        E  130.000
İstanbul   2    Veli        E  234.375
Ankara     3    Ayşe     None  339.000
Ankara     4   Fatma        K  234.000
İzmir      5  Tonguç        E  234.375

### Satır ve Kolon Ekleme / Kaldırma
![alt text](SatırVeKolonEklemeKaldırma.png)

In [43]:
ekip = ekipEfor.copy() #orjinaini etkiliemesin

#### Satır eklemem

In [44]:
df_satir = pd.DataFrame(data = {
                     "Id":[120],
                     "Ad":["XMan"],
                     "Cinsiyet":["E"],
                     "AktifMi": [True] #yeni bir kolona sahip olsun.
                    }, index=["Uzay"]
                )

#
#import pandas as pd
ekip = pd.concat([ekip,df_satir])

#

#ekip.info()
ekip=ekip.astype({"AktifMi":bool})
ekip.dtypes

Id               int64
Ad              object
Cinsiyet        object
Miktar         float16
DepartmanId     object
AktifMi           bool
dtype: object

#### Kolon Ekleme

In [45]:
#örn:  hedefin % kaçındayız.
hedef_miktar = 500

#
ekip["HedefDurum"] = ekip.Miktar/hedef_miktar #otomatik oarak en sona alır.

#istediğimiz sıradaki bir kolon haline getirebiliriz
ekip.insert(0, "HedefDurum2",ekip.Miktar/hedef_miktar)

ekip

,HedefDurum2,Id,Ad,Cinsiyet,Miktar,DepartmanId,AktifMi,HedefDurum
İstanbul,0.260,1,Ali,E,130.0,NaN,True,0.260
İstanbul,NaN,2,Veli,E,NaN,NaN,True,NaN
Ankara,0.678,3,Ayşe,None,339.0,NaN,True,0.678
Ankara,0.468,4,Fatma,K,234.0,NaN,True,0.468
İzmir,NaN,5,Tonguç,E,NaN,NaN,True,NaN
Uzay,NaN,120,XMan,E,NaN,NaN,True,NaN

#### Eval

In [46]:
#örn:
#gelecek %20 daha fazla üretmek istiyoruz.
buyumeOrani = 0.20

ekip.eval("""
            GelecekYilMiktar = Miktar * @buyumeOrani
            SonrakiYilMiktar = GelecekYilMiktar * @buyumeOrani
""", inplace=True) #orjinalini etkiler

ekip

,HedefDurum2,Id,Ad,Cinsiyet,Miktar,DepartmanId,AktifMi,HedefDurum,GelecekYilMiktar,SonrakiYilMiktar
İstanbul,0.260,1,Ali,E,130.0,NaN,True,0.260,26.00000,5.199219
İstanbul,NaN,2,Veli,E,NaN,NaN,True,NaN,NaN,NaN
Ankara,0.678,3,Ayşe,None,339.0,NaN,True,0.678,67.81250,13.562500
Ankara,0.468,4,Fatma,K,234.0,NaN,True,0.468,46.78125,9.351562
İzmir,NaN,5,Tonguç,E,NaN,NaN,True,NaN,NaN,NaN
Uzay,NaN,120,XMan,E,NaN,NaN,True,NaN,NaN,NaN

### Satır ve Kolon Kaldırmak

In [47]:
#ekip.drop("AktifMi", axis=1,inplace=True) #axis=1 ile kolon etiketini belirttiğimiz açıkladık. axis=1 ile kolon kaldırıyoruz.
#ekip.drop("Uzay", axis=0,inplace=True) #axis=0 ile satır etiketi veriyoruz.


ekip = ekip.drop(index = "İzmir", columns="Ad")
ekip

,HedefDurum2,Id,Cinsiyet,Miktar,DepartmanId,AktifMi,HedefDurum,GelecekYilMiktar,SonrakiYilMiktar
İstanbul,0.260,1,E,130.0,NaN,True,0.260,26.00000,5.199219
İstanbul,NaN,2,E,NaN,NaN,True,NaN,NaN,NaN
Ankara,0.678,3,None,339.0,NaN,True,0.678,67.81250,13.562500
Ankara,0.468,4,K,234.0,NaN,True,0.468,46.78125,9.351562
Uzay,NaN,120,E,NaN,NaN,True,NaN,NaN,NaN

### Her bir hücre için çalışan fonksyionlar
![alt text](HerBirHucreIcınCalisanFonksiyonlar.png)

In [48]:
dizi = np.random.randint(5,size=(4,5)) #0-4 arasındaki rastgele tam sayılardan 4,5'lik bir dizi üret

dizi.shape

(4, 5)

In [49]:
df = pd.DataFrame(data = dizi,
             columns=[f"col_{c}" for c in range(dizi.shape[1])] #["c1","c2"] #dizi.shape[1] ile satır değerini yani 5'i verir range 5 ise bize [0,1,2,3,4]
             ,index=[f"row_{r}" for r in range(dizi.shape[0])] #dizi.shape[0] ile satır değerini yani 4'ü veririz.
             )

df

       col_0  col_1  col_2  col_3  col_4
row_0      0      1      1      2      0
row_1      2      0      2      4      1
row_2      0      4      1      2      0
row_3      4      1      4      2      1

In [50]:
df.applymap(lambda cell: "çift" if cell%2==0 else "tek")

C:\Users\Abdullah\AppData\Local\Temp\ipykernel_5404\444744252.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda cell: "çift" if cell%2==0 else "tek")

      col_0 col_1 col_2 col_3 col_4
row_0  çift   tek   tek  çift  çift
row_1  çift  çift  çift  çift   tek
row_2  çift  çift   tek  çift  çift
row_3  çift   tek  çift  çift   tek

In [51]:
df.apply(lambda c:c.max()-c.min() , axis=0) #satır boyunca işlem yapar
df.apply(lambda c:c.max()-c.min() , axis=1) #sutun boyunca

row_0    2
row_1    4
row_2    4
row_3    3
dtype: int32

In [52]:
ekip  = ekipEfor.copy()

#
ekip.Ad.map(str.upper) #Ad serisindeki her bir adı büyük harfle yazan fonksiyonu verdik.
ekip.Ad.map(len)

İstanbul    3
İstanbul    4
Ankara      4
Ankara      5
İzmir       6
Name: Ad, dtype: int64

In [53]:
# Doğal olarak serile zaten broadcast destekler ve bunu destekleyen kendi iç fonksiyonları dışarıdakilere alternatif sunar.
ekip.Ad.str.upper()

İstanbul       ALI
İstanbul      VELI
Ankara        AYŞE
Ankara       FATMA
İzmir       TONGUÇ
Name: Ad, dtype: object

### Veri Gruplama
![alt text](VeriGruplama.png)

In [ ]:
df_groupby = ekip.groupby(by=["Cinsiyet"]) #DataFrameGroupBy

#
df_groupby.groups #grupların özetini görmemizi sağlar. Grup anahtarı ve indexler mevcut. {'E': ['İstanbul', 'İstanbul', 'İzmir'], 'K': ['Ankara']}

#
df_groupby.count() #Kolon bazında count alıyor. null olmayanların adedini veirr.

          Id  Ad  Miktar  DepartmanId
Cinsiyet
E          3   3       1            0
K          1   1       1            0

In [ ]:
df_groupby.Miktar.mean() #grup içinden bir kolona odaklanabiliriz.

Cinsiyet
E    130.0
K    234.0
Name: Miktar, dtype: float16

In [60]:
ekip.groupby(["Cinsiyet","Ad"]).sum()

                 Id  Miktar DepartmanId
Cinsiyet Ad
E        Ali      1   130.0           0
         Tonguç   5     0.0           0
         Veli     2     0.0           0
K        Fatma    4   234.0           0

#### Agg kullanımı
* min, max, mean, sum, count, std, var, first, last, mad, median, mode, prod, sem, skew, kurt, quantile, cummax, cummin, cumsum, cumprod, diff, pct_change

In [63]:
ekip_sayilar = ekip.loc[:, ["Id","Miktar"]]
#ekip.select_dtypes()

#--------------
ekip_sayilar.agg(["count","max","min","sum"])

       Id  Miktar
count   5     3.0
max     5   339.0
min     1   130.0
sum    15   703.0

In [65]:
ekip.agg({
    "Id":["max","min","count"],
    "Miktar":["count","max","min","sum","std"],
    "Cinsiyet":["count"]
}).fillna("-") #eksik değerler için - bassın

        Id  Miktar Cinsiyet
max    5.0   339.0        -
min    1.0   130.0        -
count  5.0     3.0      4.0
sum      -   703.0        -
std      -   104.5        -

#### groupby ve agg

In [72]:
df_hiyerarsik = ekip.groupby(by=["Cinsiyet"]).agg({
                                    "Miktar":["sum","max","min"],
                                    "Id":["max","min"]
})

df_hiyerarsik

         Miktar                Id
            sum    max    min max min
Cinsiyet
E         130.0  130.0  130.0   5   1
K         234.0  234.0  234.0   4   4

In [ ]:
df_hiyerarsik.reset_index()

#
df_hiyerarsik.loc[: , ("Miktar" , ["max","min"])] #hiyeraşideki değerleir bu şekilde okuyabiliriz.

         Miktar
            max    min
Cinsiyet
E         130.0  130.0
K         234.0  234.0

### Birden Fazla DF'i Birleştirmek
![alt text](BirdenFazlaDFBirleştirme.png)

In [77]:
departman
ekip.DepartmanId  = [1,2,3,1,2]

In [80]:
departman

   DepId        DepAd
0      1  Departman A
1      2  Departman B
2      3  Departman C

#### merge

In [ ]:
# departman
# ekip

#
pd.merge(ekip, departman, how="left", left_on = "DepartmanId", right_on="DepId") #left joine tekabül eder. how="left"
pd.merge(ekip, departman, how="right", left_on = "DepartmanId", right_on="DepId") #right
pd.merge(ekip, departman, how="inner", left_on = "DepartmanId", right_on="DepId") #inner
pd.merge(ekip, departman, how="outer", left_on = "DepartmanId", right_on="DepId") #outer yani full join

   Id      Ad Cinsiyet  Miktar  DepartmanId  DepId        DepAd
0   1     Ali        E   130.0            1      1  Departman A
1   4   Fatma        K   234.0            1      1  Departman A
2   2    Veli        E     NaN            2      2  Departman B
3   5  Tonguç        E     NaN            2      2  Departman B
4   3    Ayşe     None   339.0            3      3  Departman C

#### join
- index etiketleri üzerinden eşleştirir

In [ ]:
ekip.set_index("DepartmanId",inplace=True)
departman.set_index("DepId", inplace=True)

#
ekip.join(departman, how="left")

          Id      Ad Cinsiyet  Miktar  DepartmanId
İstanbul   1     Ali        E   130.0            1
İstanbul   2    Veli        E     NaN            2
Ankara     3    Ayşe     None   339.0            3
Ankara     4   Fatma        K   234.0            1
İzmir      5  Tonguç        E     NaN            2